# Generated by Django 4.2.7 on 2023-11-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableLaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laser', models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Purple', 'Purple')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('laser', models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Purple', 'Purple')], max_length=10)),
            ],
        ),
    ]
