# Generated by Django 4.2.7 on 2023-11-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laser',
            name='color',
            field=models.CharField(default='#777777', max_length=30),
        ),
    ]
