# Generated by Django 4.2.7 on 2023-11-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_laser_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laser',
            name='color',
            field=models.CharField(default='#777777', max_length=30, null=True),
        ),
    ]
